<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Stagem Team
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_ZfcPool
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php use Stagem\ZfcPool\Service\PoolService; ?>
<?php
// @todo Create PoolBlock with method getPools() which allow add Default Configuration pull on demand with option "includeDefault".
// @todo This allow avoid duplicate code.
// @todo PoolInterface must contain getId(), getMnemo(), getName() methods. These methods must be used in pool switcher
?>
<?php if (!$this->pool()->isSingleMode()) : ?>
	<?php $current = $this->pool()->current(); ?>
	<div class="pool-switcher pull-right">
		<select class="form-control">
	        <?php $pools = $this->pool()->getPools(); ?>
			<?php foreach ($pools as $pool) : ?>
		        <?php $selected = ''; ?>
		        <?php if ($pool->getId() === $current->getId()) : ?>
		            <?php $selected = 'selected="selected"' ?>
		        <?php endif; ?>
				<option value="<?= $pool->getId() ?>" <?= $selected ?> data-url="<?= $this->url(
		                //$this->current('routeName'),
		                'admin/default/wildcard',
		                array_merge($this->current('routeParams'), [$this->config('pool/general/url_parameter') => $pool->getId()])
						// @todo Create ConfigHelper in Core and call $this->config('pool/general/url_parameter')
		                //['query' => [$this->sysConfig('pool/general/url_parameter') => $pool->getName()]]
					)?>"
				><?= $pool->getName() ?></option>
		    <?php endforeach;; ?>

	        <?php if ($this->vars('includeDefault') || true) : ?>
	            <?php $selected = ''; ?>
	            <?php if (PoolService::POOL_ADMIN === $current->getId()) : ?>
	                <?php $selected = 'selected="selected"' ?>
	            <?php endif; ?>
				<option value="0" <?= $selected ?> data-url="<?= $this->url(
	                'admin/default/wildcard',
	                array_merge($this->current('routeParams'), [$this->config('pool/general/url_parameter') => PoolService::POOL_ADMIN])

	            //['query' => [$this->sysConfig('pool/general/url_parameter') => $pool->getName()]]
	            )?>"
				><?= $this->translate('Default Configuration') ?></option>
	        <?php endif; ?>

		</select>
	</div>
<?php endif; ?>